In [2]:

import numpy as np
import random
import scipy.stats  as sps

In [42]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j), здесь i -- число строк,
# j -- число столбцов.
x=1000
y=1000
a = np.random.sample((x,y))
b = np.random.sample((x,y))
# выведите ранг каждой матрицы с помощью функции np.linalg.rank.
# Используйте функцию shape, что она вывела?
# ========
arank = np.linalg.matrix_rank(a)
brank = np.linalg.matrix_rank(b)
print (arank)
print (brank)

# ========


1000
1000


In [43]:
a.shape
b.shape

(1000, 1000)

In [44]:
print (a)
print (b)

[[0.97795368 0.22749922 0.90650596 ... 0.49632393 0.53883561 0.79226981]
 [0.76099945 0.24476464 0.61441333 ... 0.19166012 0.97319874 0.412404  ]
 [0.38605318 0.83673263 0.53017266 ... 0.03334817 0.24691903 0.20475612]
 ...
 [0.37883447 0.04363684 0.35564911 ... 0.94675476 0.9974136  0.39449995]
 [0.1110792  0.22779067 0.01651691 ... 0.50719991 0.26318663 0.83019876]
 [0.30271381 0.35795771 0.85854882 ... 0.41760513 0.61810493 0.76653731]]
[[0.16591512 0.34695464 0.2426861  ... 0.86006367 0.34003178 0.16186613]
 [0.63890171 0.52312944 0.16474832 ... 0.50576893 0.47333133 0.40249538]
 [0.37431524 0.02939377 0.23567785 ... 0.39153479 0.55391821 0.00162016]
 ...
 [0.57840946 0.43964301 0.72077114 ... 0.13599901 0.45050437 0.26552706]
 [0.20050004 0.3174921  0.70687815 ... 0.21948658 0.75008377 0.90446919]
 [0.51275746 0.36375143 0.25309311 ... 0.17548898 0.23827013 0.47585247]]


In [53]:
# здесь напишите перемножение матриц без 
# использования NumPy и выведите результат
def mult(a,b):
    print (a*b)
mult (a,b)
pass

[[1.62257300e-01 7.89319121e-02 2.19996392e-01 ... 4.26870183e-01
  1.83221231e-01 1.28241651e-01]
 [4.86203850e-01 1.28043589e-01 1.01223562e-01 ... 9.69357342e-02
  4.60645453e-01 1.65990707e-01]
 [1.44505591e-01 2.45947296e-02 1.24949952e-01 ... 1.30569679e-02
  1.36772944e-01 3.31736839e-04]
 ...
 [2.19121439e-01 1.91846327e-02 2.56341612e-01 ... 1.28757706e-01
  4.49339182e-01 1.04750413e-01]
 [2.22713831e-02 7.23217377e-02 1.16754458e-02 ... 1.11323572e-01
  1.97412022e-01 7.50889196e-01]
 [1.55218762e-01 1.30207629e-01 2.17292789e-01 ... 7.32850988e-02
  1.47275939e-01 3.64758674e-01]]


In [55]:
def np_mult(a,b):
    # здесь напишите перемножение матриц с
    # использованием NumPy и выведите результат
    print (np.dot (a,b))
np_mult (a,b)
pass

[[254.69606657 257.67829719 256.72370439 ... 257.84795541 255.37848359
  252.51628121]
 [245.33762025 249.01388274 254.34569949 ... 250.62285047 243.06794256
  244.12006097]
 [243.04938856 246.61048435 244.6264957  ... 250.84487176 237.72809557
  242.58038758]
 ...
 [248.8422567  252.65840921 252.07635945 ... 252.51115256 248.53480176
  245.41167857]
 [252.72669929 251.48079004 250.18539166 ... 252.94046455 246.95634562
  245.40055739]
 [255.99727095 262.08380603 257.45782606 ... 262.16324626 255.19245752
  249.67255659]]


In [56]:
%%time
 # засечем время работы функции без NumPy# засеч 
mult(a,b)

[[1.62257300e-01 7.89319121e-02 2.19996392e-01 ... 4.26870183e-01
  1.83221231e-01 1.28241651e-01]
 [4.86203850e-01 1.28043589e-01 1.01223562e-01 ... 9.69357342e-02
  4.60645453e-01 1.65990707e-01]
 [1.44505591e-01 2.45947296e-02 1.24949952e-01 ... 1.30569679e-02
  1.36772944e-01 3.31736839e-04]
 ...
 [2.19121439e-01 1.91846327e-02 2.56341612e-01 ... 1.28757706e-01
  4.49339182e-01 1.04750413e-01]
 [2.22713831e-02 7.23217377e-02 1.16754458e-02 ... 1.11323572e-01
  1.97412022e-01 7.50889196e-01]
 [1.55218762e-01 1.30207629e-01 2.17292789e-01 ... 7.32850988e-02
  1.47275939e-01 3.64758674e-01]]
Wall time: 8.98 ms


In [57]:
%%time
# засечем время работы функции с NumPy
np_mult(a,b)

[[254.69606657 257.67829719 256.72370439 ... 257.84795541 255.37848359
  252.51628121]
 [245.33762025 249.01388274 254.34569949 ... 250.62285047 243.06794256
  244.12006097]
 [243.04938856 246.61048435 244.6264957  ... 250.84487176 237.72809557
  242.58038758]
 ...
 [248.8422567  252.65840921 252.07635945 ... 252.51115256 248.53480176
  245.41167857]
 [252.72669929 251.48079004 250.18539166 ... 252.94046455 246.95634562
  245.40055739]
 [255.99727095 262.08380603 257.45782606 ... 262.16324626 255.19245752
  249.67255659]]
Wall time: 90.8 ms
